---
title: "Untitled"
output: html_document
date: "2024-11-21"
---

```{r load-libraries, echo=F, message=F}
library(tidyverse)
library(magrittr)
library(patchwork)
library(RcppRoll)
library(readxl)
library(lubridate)
library(scales)
library(splines)
library(here)
```

```{r}
# Midwest 
Midwest_summary_1 <- read_csv(file = here("Data", "Midwest-weekly-smoothed.csv"))
Midwest_summary_2 <- read_csv(file = here("Data", "Midwest-weekly-smoothed-2.csv"))

Midwest_summary <- bind_rows(Midwest_summary_1, Midwest_summary_2)

Midwest_summary %<>% mutate(p2_check = case_when(dt3 < as.Date("2015-10-04") ~ p1/num_test_p1,
                                               dt3 >= as.Date("2015-10-04") ~ p1/num_test),
                              
                              num_test_both = case_when(dt3 < as.Date("2015-10-04") ~ num_test_p1,
                                               dt3 >= as.Date("2015-10-04") ~ num_test),
                              
                              diff = p2 - p2_check)

# West 
West_summary_1 <- read_csv(file = here("Data", "West-weekly-smoothed.csv"))
West_summary_2 <- read_csv(file = here("Data", "West-weekly-smoothed-2.csv"))

West_summary <- bind_rows(West_summary_1, West_summary_2)

West_summary %<>% mutate(p2_check = case_when(dt3 < as.Date("2015-10-04") ~ p1/num_test_p1,
                                               dt3 >= as.Date("2015-10-04") ~ p1/num_test),
                              
                              num_test_both = case_when(dt3 < as.Date("2015-10-04") ~ num_test_p1,
                                               dt3 >= as.Date("2015-10-04") ~ num_test),
                              
                              diff = p2 - p2_check)

# Northeast
Northeast_summary_1 <- read_csv(file = here("Data", "Northeast-weekly-smoothed.csv"))
Northeast_summary_2 <- read_csv(file = here("Data", "Northeast-weekly-smoothed-2.csv"))

Northeast_summary <- bind_rows(Northeast_summary_1, Northeast_summary_2)

Northeast_summary %<>% mutate(p2_check = case_when(dt3 < as.Date("2015-10-04") ~ p1/num_test_p1,
                                               dt3 >= as.Date("2015-10-04") ~ p1/num_test),
                              
                              num_test_both = case_when(dt3 < as.Date("2015-10-04") ~ num_test_p1,
                                               dt3 >= as.Date("2015-10-04") ~ num_test),
                              
                              diff = p2 - p2_check)

# South
South_summary_1 <- read_csv(file = here("Data", "South-weekly-smoothed.csv"))
South_summary_2 <- read_csv(file = here("Data", "South-weekly-smoothed-2.csv"))

South_summary <- bind_rows(South_summary_1, South_summary_2)

South_summary %<>% mutate(p2_check = case_when(dt3 < as.Date("2015-10-04") ~ p1/num_test_p1,
                                               dt3 >= as.Date("2015-10-04") ~ p1/num_test),
                          num_test_both = case_when(dt3 < as.Date("2015-10-04") ~ num_test_p1,
                                               dt3 >= as.Date("2015-10-04") ~ num_test),
                          diff = p2 - p2_check)

ggplot(South_summary, aes(x = dt3, y = diff)) + geom_line()
min(South_summary$diff)
max(South_summary$diff)
South_summary %>% select(dt3, p2, p1, num_test, p2_check, diff) %>% View()



Northeast_summary %<>% mutate(p2_check = p2/num_test)
Northeast_summary %>% select(dt3, p2, p1, num_test, p2_check) %>% View()
```

```{r}
NE <- Northeast_summary %>% select(dt3, p1, num_test_both) %>% mutate(region = "NE")
South <- South_summary %>% select(dt3, p1, num_test_both) %>% mutate(region = "S")
West <- West_summary %>% select(dt3, p1, num_test_both) %>% mutate(region = "W")
MW <- Midwest_summary %>% select(dt3, p1, num_test_both) %>% mutate(region = "MW")

all <- bind_rows(NE, South, West, MW)

regions_wide <- all %>% pivot_wider(names_from = region, values_from = c(p1, num_test_both))


#Add in the other regions
regions_wide %<>% mutate(total_pos = p1_NE + p1_S + p1_MW + p1_W,
  total_tests = num_test_both_NE + num_test_both_S + num_test_both_MW + num_test_both_W, 
  proportion_pos = total_pos/total_tests)

ggplot(regions_wide, aes(x = dt3, y = proportion_pos)) + geom_line() + 
  theme_bw() + 
  labs(y = "Proportion positive", x = "Date") +
  geom_hline(yintercept = 0.11) + 
  geom_hline(yintercept = 0.20) 
```

```{r}
regions_wide %>% head()

regions_wide %<>% mutate(month = month(dt3), 
                          year = year(dt3))

regions_wide2 <- regions_wide %>% 
  filter(dt3 < as.Date("2020-07-01")) %>%
  group_by(month) %>%
  summarise(sum_p1 = sum(total_pos),
            sum_tests = sum(total_tests),
            agg_pos = sum_p1/sum_tests)
  
ggplot(regions_wide2, aes( x= month, y = agg_pos)) + 
  geom_line() + 
  geom_point() + 
  theme_bw() +
  scale_x_continuous(breaks = 1:12) + 
  geom_hline(yintercept = 0.05)


regions_wide3 <- regions_wide %>% 
  filter(dt3 < as.Date("2020-07-01") & year != 2009) %>%
  group_by(month) %>%
  summarise(sum_p1 = sum(total_pos),
            sum_tests = sum(total_tests),
            agg_pos = sum_p1/sum_tests)

regions_wide3 %<>% mutate(oct_first = as.numeric(factor(month, levels = c(10, 11, 12, 1:9))))

ggplot(regions_wide3, aes( x= oct_first, y = agg_pos)) + 
  geom_rect(aes(xmin = 1, xmax = 12, ymin = 0, ymax = 0.05), fill = "grey", alpha = 0.7) +
  geom_rect(aes(xmin = 1, xmax = 12, ymin = 0.05, ymax = 0.11), fill = "#fdae61", alpha = 0.7) +
  geom_rect(aes(xmin = 1, xmax = 12, ymin = 0.11, ymax = 0.199), fill = "#ffffbf", alpha = 0.7) +
  geom_rect(aes(xmin = 1, xmax = 12, ymin = 0.2, ymax = 0.3), fill = "#a6d96a", alpha = 0.7) +
  geom_point() + theme_bw() + geom_line() + 
  scale_x_continuous(breaks = c(1:12), 
                     labels = c("Oct", "Nov", "Dec", "Jan", "Feb", "Mar", "Apr",
                                "May", "Jun", "Jul", "Aug", "Sep" )) + 
  geom_hline(yintercept = 0.05) + geom_line() + 
  labs(y = "Average percent positive", x = "Month") 
  
ggsave(filename = here("images", "agg-regions-monthly-risk.png"), device = "png", dpi = 300, width = 5, height= 5, plot = last_plot())



```

```{r}
regions_wide_select <- regions_wide %>% select(dt3, month, year, proportion_pos)

regions_wide_select %<>% mutate(flu_risk = case_when(proportion_pos < 0.11 ~ "1: low",
                                                     proportion_pos >= 0.11 & proportion_pos < 0.20 ~ "2: med",
                                                     proportion_pos >= 0.20 ~ "3: high"))

table(regions_wide_select$flu_risk)

ggplot(regions_wide_select %>% filter(dt3 < as.Date("2020-07-01")), 
       aes(x = dt3, y = proportion_pos)) + geom_line() + 
  geom_point(aes(col = flu_risk)) +
  theme_bw() + 
  labs(y = "Proportion positive", x = "Date") +
  geom_hline(yintercept = 0.11) + 
  geom_hline(yintercept = 0.20) +
  scale_x_date(date_breaks = "years", date_labels = "%y") +
  scale_color_manual(values = c("#4d9221","grey", "#c51b7d" )) +
  labs(y = "% positive flu tests", x = "Year") 

ggsave(filename = here("images", "agg-regions-weekly-risk.png"), device = "png", dpi = 300, width = 20, height= 5, plot = last_plot())
```

```{r}
write_csv(regions_wide_select, file = here("Data", "all-regions-aggregated-risk-groups-weekly.csv"))
```
